name = "img"
main = "./src/index.js"
compatibility_date = "2022-11-08"

kv_namespaces = [
  { binding = "link", id = "662f3dcee64c48eea66955806bda8a82",preview_id='662f3dcee64c48eea66955806bda8a82'}
]
[site]
bucket = "./static/dist"
